# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RyanShop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RyanShop
  pod 'RxSwift', '5.0.0'
  pod 'RxCocoa', '5.0.0'

end
